### ISSUE TITLE
Phavu files

### ISSUE THREAD

**Issue by svengato** [legumeinfo/aeschynomenemine#1]
There are bean files listed in project.xml (lines 14-25) -- is this correct?

**Comment by sammyjava** [comment]
Yes, as the comment says: TEMPORARY FOR PATHWAY DERIVATION. I load known pathways for similar species to create new pathway files using gene family membership. Once those pathway files are derived, the temp loads can be removed.

**Comment by adf-ncgr** [comment]
Oh, I think I understand that now- can explain further if needed @svengato, sorry for not snapping to it earlier when you asked me.

**Comment by sammyjava** [comment]
That being said, I may forget sometimes to rebuild without the extra species. I'm using IM to find the pathways simply because it's easy to do with a query. One could write a standalone proggy (as the Brits say) instead.
